def generate_html(title, heading, paragraph):
    """
    Generate a simple HTML page.

    :param title: The title of the page.
    :param heading: The heading of the page.
    :param paragraph: The paragraph content of the page.
    """
    html = f"""
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>{title}</title>
    </head>
    <body>
        <h1>{heading}</h1>
        <p>{paragraph}</p>
    </body>
    </html>
    """
    return html

def write_to_file(filename, content):
    """
    Write content to a file.

    :param filename: The name of the file to write to.
    :param content: The content to write.
    """
    with open(filename, 'w') as f:
        f.write(content)

def main():
    title = "Hello World"
    heading = "Welcome to Hello World"
    paragraph = "This is a simple HTML page generated by Python."
    filename = "index.html"

    html = generate_html(title, heading, paragraph)
    write_to_file(filename, html)
    print(f"HTML file generated: {filename}")

if __name__ == "__main__":
    main()
